type Images ={
  [file_name_without_suffix: string]: string // for now use path to science icon in /static/
}

const images: Images = {
  'dynamic-data-collection': '/thumbnails/DDCstatepic.png',
  'llm-generation': '/thumbnails/llm-generation.png',
  'autonomous-camera-control': '/thumbnails/autonomous-camera-control.jpg',
  'lidar-sky-solar': '/thumbnails/lidar-sky-solar-icon.png',
  'resource-management': '/thumbnails/resource-management-icon.png',
  'super-resolution': '/thumbnails/super-resolution.png',
  'sound-separation': '/thumbnails/sound-separation.png',
  'finding-events': '/thumbnails/finding-events.png',
  'collaboration': '/thumbnails/collaboration-icon.jpg',
  'solar-irradiance-estimation': '/thumbnails/solar-irradiance.jpg',
  'smoke-detection': '/thumbnails/smoke-detection.png',
  'rideshare-detection': '/thumbnails/rideshare-detection.png',
  'lightning-detector': '/thumbnails/lightning-detector.jpg',
  'snow-detection': '/thumbnails/snow-detection.jpg',
  'scalable-ci-in-aps': '/thumbnails/scalable-ci-in-aps-icon.png',
  'traffic-state-estimation': '/thumbnails/traffic-state-est.png',
  'traffic-counter': '/thumbnails/traffic-cnt.jpg',
  'wildfire-science': '/thumbnails/wildfire-icon-1.jpg',
  'snowflake': '/thumbnails/snowflake-icon.jpg',
  'water-segmentation': '/thumbnails/water_seg-icon.jpg',
  'monitoring-biodiversity': '/thumbnails/bar-lt_panel-2048x689-2.jpg',
  'water-level-detection': '/thumbnails/water_level-icon.jpg',
  'vehicle-tracking': '/thumbnails/vehicle_track-icon.jpg',
  'characterizing-clouds': '/thumbnails/cloud-icon.jpg',
  'lightning-science': '/thumbnails/lightning-icon2-1.jpg',
  'bandwidth-aware-learning': '/thumbnails/bandwidth-icon.png',
  'social-distancing': '/thumbnails/social_distance-icon.jpg',
  'nowcasting-weather': '/thumbnails/nowcasting-icon.jpg',
  'integrating-chameleon': '/thumbnails/chameleon_integration-icon.jpg',
  'sagebat': '/thumbnails/sagebat.png',
  'sageair-intelligence': '/thumbnails/sageair-intelligence.png',
  'manoomin-detection': '/thumbnails/manoomin-detection.png',
  'dangerous-animal-detection': '/thumbnails/dangerous-animal-detection.png',
  'drought-early-warning': '/thumbnails/drought-early-warning.png',
  'bisonn': '/thumbnails/bisonn.png',
  'mortimus-urgent-scheduling': '/thumbnails/mortimus-urgent-scheduling.png',
  'sage-bat-counter': '/thumbnails/sage-bat-counter.png',
  'sage-flashpoint': '/thumbnails/sage-flashpoint.png',
  'image-search-at-the-edge': '/thumbnails/image-search-at-the-edge.png',
  'weather-image-classification': '/thumbnails/weather-image-classification.png',
  'sage-ndp-scidx-mcp': '/thumbnails/sage-ndp-scidx-mcp.png',
  'sage-halow': '/thumbnails/sage-halow.png',
  'speech-redaction-at-the-edge': '/thumbnails/speech-redaction-at-the-edge.png',
}

export default images
